<?php
    $DEVICE_TYPE_SERVER = 1;
    $DEVICE_TYPE_CLIENT = 2;
    
    $REQUEST_TYPE_QUERY_SENSOR_LIST = 1;
    $REQUEST_TYPE_QUERY_SENSOR_INFO = 2;
    
    $SENSOR_TYPE_LIGHT = 0;
    $SENSOR_TYPE_ELECTRICITY = 1;
    $SENSOR_TYPE_MOTION = 2;
    $SENSOR_TYPE_SWITCH = 3;
    $SENSOR_TYPE_IR = 4;
    // keep in sync with STM32 and Android
?>